---
title: Configure Windows Media Player
description: Configures Windows Media Player for the optimal privacy, security and usability
actions:
  - !registryValue:
    path: 'HKLM\SOFTWARE\Policies\Microsoft\WMDRM'
    value: "DisableOnline"
    data: "1"
    type: REG_DWORD

  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\MediaPlayer\Preferences'
    value: "AcceptedPrivacyStatement"
    data: "1"
    type: REG_DWORD

  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\MediaPlayer\Preferences'
    value: "UsageTracking"
    data: "0"
    type: REG_DWORD
